AWSTemplateFormatVersion: "2010-09-09"

Description: Creates the necessary components for Authentication Frontend application secure pipeline migration testing

Parameters:
  Environment:
    Description: The name of the environment to deploy to
    Type: String
    AllowedValues:
      - dev
      - build
      - staging
      - integration
      - production

  EndpointSuffix:
    Description: |
      (Optional) domain suffix i.e. -sp. Example output FQDN - signin-sp.build.account.gov.uk
    Type: String
    Default: ""
    AllowedPattern: '[a-z0-9-]*'
    ConstraintDescription: |
      must be a valid domain name, consists of lowercase letters, numbers and hyphens OR blank

  DeployHostedZone:
    Description: |
      Deploy the Route53 hosted zone and associated SSM parameter
    Type: String
    AllowedValues:
      - "Yes"
      - "No"
    Default: "Yes"

  DeployCertificate:
    Description: |
      Deploy domain certificate and associated SSM parameter
    Type: String
    AllowedValues:
      - "Yes"
      - "No"
    Default: "No"

Mappings:
  EndpointConfigs:
    Auth:
      lowercaseName: auth
    Manage:
      lowercaseName: manage
    Oidc:
      lowercaseName: oidc
    Signin:
      lowercaseName: signin

Conditions:
  CreateDevEnvironmentResources: !Equals
    - !Ref Environment
    - dev

  CreateNonProdEnvironmentResources: !Or
    - !Equals
      - !Ref Environment
      - build
    - !Equals
      - !Ref Environment
      - staging
    - !Equals
      - !Ref Environment
      - integration

  CreateProductionEnvironmentResources: !Equals
    - !Ref Environment
    - production

  CreateDevHostedZone: !And
    - !Condition CreateDevEnvironmentResources
    - !Equals
      - !Ref DeployHostedZone
      - "Yes"

  CreateDevCertificate: !And
    - !Condition CreateDevEnvironmentResources
    - !Equals
      - !Ref DeployHostedZone
      - "Yes"
    - !Equals
      - !Ref DeployCertificate
      - "Yes"

  CreateNonProdHostedZone: !And
    - !Condition CreateNonProdEnvironmentResources
    - !Equals
      - !Ref DeployHostedZone
      - "Yes"

  CreateNonProdCertificate: !And
    - !Condition CreateNonProdEnvironmentResources
    - !Equals
      - !Ref DeployHostedZone
      - "Yes"
    - !Equals
      - !Ref DeployCertificate
      - "Yes"

  CreateProductionHostedZone: !And
    - !Condition CreateProductionEnvironmentResources
    - !Equals
      - !Ref DeployHostedZone
      - "Yes"

  CreateProductionCertificate: !And
    - !Condition CreateProductionEnvironmentResources
    - !Equals
      - !Ref DeployHostedZone
      - "Yes"
    - !Equals
      - !Ref DeployCertificate
      - "Yes"

Transform: AWS::LanguageExtensions

Resources:

  # ==============================
  # dev hosted zones and resources
  # ==============================
  Fn::ForEach::DevEnvironments:
    - EnvName
    - - authdev1
      - authdev2
    - ${EnvName}HostedZone:
        Type: AWS::Route53::HostedZone
        Condition: CreateDevHostedZone
        DeletionPolicy: Retain
        UpdateReplacePolicy: Retain
        Properties:
          Name: !Sub ${EnvName}.${Environment}.account.gov.uk
      Fn::ForEach::Endpoints:
        - Endpoint
        - - signin

          # - auth
          # - manage
          # - oidc
        - ${EnvName}${Endpoint}HostedZone:
            Type: AWS::Route53::HostedZone
            Condition: CreateDevHostedZone
            DeletionPolicy: Retain
            UpdateReplacePolicy: Retain
            Properties:
              Name: !Sub ${Endpoint}.${EnvName}.${Environment}.account.gov.uk
          ${EnvName}${Endpoint}DevDelegation:
            Type: AWS::Route53::RecordSet
            Condition: CreateDevHostedZone
            Properties:
              Name: !Sub ${Endpoint}.${EnvName}.${Environment}.account.gov.uk
              Type: NS
              HostedZoneId: !Ref
                Fn::Sub: ${EnvName}HostedZone
              ResourceRecords: !GetAtt
                - !Sub ${EnvName}${Endpoint}HostedZone
                - NameServers
              TTL: 60
          ${EnvName}${Endpoint}HostedZoneSSM:
            Type: AWS::SSM::Parameter
            Condition: CreateDevHostedZone
            Properties:
              Description: !Sub "The ${Endpoint} subdomain Public Hosted Zone Id"
              Name: !Sub "/deploy/${EnvName}/${Endpoint}${EndpointSuffix}_route53_hostedzone_id"
              Type: String
              Value: !Ref
                Fn::Sub: ${EnvName}${Endpoint}HostedZone
              Tags:
                Environment: !Sub ${EnvName}
                Application: auth-frontend
                Source: govuk-one-login/authentication-frontend/cloudformation/domains/template.yaml
          ${EnvName}${Endpoint}Certificate:
            Type: AWS::CertificateManager::Certificate
            Condition: CreateDevCertificate
            Properties:
              DomainName: !Sub ${Endpoint}.${EnvName}.${Environment}.account.gov.uk
              DomainValidationOptions:
                - DomainName: !Sub ${Endpoint}.${EnvName}.${Environment}.account.gov.uk
                  HostedZoneId: !GetAtt
                    - !Sub ${EnvName}${Endpoint}HostedZone
                    - Id
              ValidationMethod: DNS
          ${EnvName}${Endpoint}CertificateArnSSM:
            Type: AWS::SSM::Parameter
            Condition: CreateDevCertificate
            Properties:
              Description: !Sub "The ${Endpoint} subdomain Certificate ARN"
              Name: !Sub "/deploy/${EnvName}/${Endpoint}${EndpointSuffix}_certificate_arn"
              Type: String
              Value: !Ref
                Fn::Sub: ${EnvName}${Endpoint}Certificate
              Tags:
                Environment: !Sub ${EnvName}
                Application: auth-frontend
                Source: govuk-one-login/authentication-frontend/cloudformation/domains/template.yaml

  # ===================================
  # Non-prod hosted zones and resources
  # ===================================
  Fn::ForEach::Endpoints:
    - Endpoint
    - - Signin

      # - Auth
      # - Manage
      # - Oidc
    - Accounts${Endpoint}HostedZone:
        Type: AWS::Route53::HostedZone
        Condition: CreateNonProdHostedZone
        DeletionPolicy: Retain
        UpdateReplacePolicy: Retain
        Properties:
          Name: !Sub
            - ${lowercaseEndpoint}${EndpointSuffix}.${Environment}.account.gov.uk
            - lowercaseEndpoint: !FindInMap
                - EndpointConfigs
                - !Ref Endpoint
                - lowercaseName
      Accounts${Endpoint}HostedZoneSSM:
        Type: AWS::SSM::Parameter
        Condition: CreateNonProdHostedZone
        Properties:
          Description: !Sub "The ${Endpoint} subdomain Public Hosted Zone Id"
          Name: !Sub
            - /deploy/${Environment}/${lowercaseEndpoint}${EndpointSuffix}_route53_hostedzone_id
            - lowercaseEndpoint: !FindInMap
                - EndpointConfigs
                - !Ref Endpoint
                - lowercaseName
          Type: String
          Value: !Ref
            Fn::Sub: Accounts${Endpoint}HostedZone
          Tags:
            Environment: !Ref Environment
            Application: auth-frontend
            Source: govuk-one-login/authentication-frontend/cloudformation/domains/template.yaml
      Accounts${Endpoint}Certificate:
        Type: AWS::CertificateManager::Certificate
        Condition: CreateNonProdCertificate
        Properties:
          DomainName: !Sub ${Endpoint}${EndpointSuffix}.${Environment}.account.gov.uk
          DomainValidationOptions:
            - DomainName: !Sub ${Endpoint}${EndpointSuffix}.${Environment}.account.gov.uk
              HostedZoneId: !GetAtt
                - !Sub Accounts${Endpoint}HostedZone
                - Id
          ValidationMethod: DNS
      Accounts${Endpoint}CertificateArnSSM:
        Type: AWS::SSM::Parameter
        Condition: CreateNonProdCertificate
        Properties:
          Description: !Sub "The ${Endpoint} subdomain Certificate ARN"
          Name: !Sub
            - /deploy/${Environment}/${lowercaseEndpoint}${EndpointSuffix}_certificate_arn
            - lowercaseEndpoint: !FindInMap
                - EndpointConfigs
                - !Ref Endpoint
                - lowercaseName
          Type: String
          Value: !Ref
            Fn::Sub: Accounts${Endpoint}Certificate
          Tags:
            Environment: !Ref Environment
            Application: auth-frontend
            Source: govuk-one-login/authentication-frontend/cloudformation/domains/template.yaml

  # =====================================
  # Production hosted zones and resources
  # =====================================
  Fn::ForEach::ProdEndpoints:
    - Endpoint
    - - Signin

      # For services not yet migrated to secure pipelines, the corresponding domain and resources are commented out in prod
      # - Auth
      # - Manage
      # - Oidc
    - Accounts${Endpoint}ProdHostedZone:
        Type: AWS::Route53::HostedZone
        Condition: CreateProductionHostedZone
        DeletionPolicy: Retain
        UpdateReplacePolicy: Retain
        Properties:
          Name: !Sub ${Endpoint}${EndpointSuffix}.account.gov.uk
      Accounts${Endpoint}ProdHostedZoneSSM:
        Type: AWS::SSM::Parameter
        Condition: CreateProductionHostedZone
        Properties:
          Description: !Sub "The ${Endpoint} subdomain Public Hosted Zone Id"
          Name: !Sub
            - /deploy/${Environment}/${lowercaseEndpoint}${EndpointSuffix}_route53_hostedzone_id
            - lowercaseEndpoint: !FindInMap
                - EndpointConfigs
                - !Ref Endpoint
                - lowercaseName
          Type: String
          Value: !Ref
            Fn::Sub: Accounts${Endpoint}ProdHostedZone
          Tags:
            Environment: !Ref Environment
            Application: auth-frontend
            Source: govuk-one-login/authentication-frontend/cloudformation/domains/template.yaml
      Accounts${Endpoint}ProdCertificate:
        Type: AWS::CertificateManager::Certificate
        Condition: CreateProductionCertificate
        Properties:
          DomainName: !Sub ${Endpoint}${EndpointSuffix}.account.gov.uk
          DomainValidationOptions:
            - DomainName: !Sub ${Endpoint}${EndpointSuffix}.account.gov.uk
              HostedZoneId: !GetAtt
                - !Sub Accounts${Endpoint}ProdHostedZone
                - Id
          ValidationMethod: DNS
      Accounts${Endpoint}ProdCertificateArnSSM:
        Type: AWS::SSM::Parameter
        Condition: CreateProductionCertificate
        Properties:
          Description: !Sub "The ${Endpoint} subdomain Certificate ARN"
          Name: !Sub
            - /deploy/${Environment}/${lowercaseEndpoint}${EndpointSuffix}_certificate_arn
            - lowercaseEndpoint: !FindInMap
                - EndpointConfigs
                - !Ref Endpoint
                - lowercaseName
          Type: String
          Value: !Ref
            Fn::Sub: Accounts${Endpoint}ProdCertificate
          Tags:
            Environment: !Ref Environment
            Application: auth-frontend
            Source: govuk-one-login/authentication-frontend/cloudformation/domains/template.yaml
