AWSTemplateFormatVersion: "2010-09-09"

Description: >-
  Creates the necessary components for Authentication Frontend application secure pipeline migration testing

Parameters:
  Environment:
    Description: The name of the environment to deploy to
    Type: String
    AllowedValues:
      - build
      - staging

Resources:
  #
  # auth
  #
  AccountsAuthHostedZone:
    Type: AWS::Route53::HostedZone
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      Name: !Sub auth-sp.${Environment}.account.gov.uk

  AccountsAuthHostedZoneSSM:
    Type: AWS::SSM::Parameter
    Properties:
      Description: The Auth subdomain Public Hosted Zone Id
      Name: !Sub "/deploy/${Environment}/auth_route53_hostedzone_id"
      Type: String
      Value: !Ref AccountsAuthHostedZone
      Tags:
        Environment: !Ref Environment
        Application: "auth-frontend"
        Source: govuk-one-login/authentication-frontend/cloudformation/domains/template.yaml

  AccountsAuthCertificate:
    Type: AWS::CertificateManager::Certificate
    Properties:
      DomainName: !Sub auth-sp.${Environment}.account.gov.uk
      DomainValidationOptions:
        - DomainName: !Sub auth-sp.${Environment}.account.gov.uk
          HostedZoneId: !GetAtt AccountsAuthHostedZone.Id
      ValidationMethod: DNS

  AccountsAuthCertificateArnSSM:
    Type: AWS::SSM::Parameter
    Properties:
      Description: The Auth subdomain Certificate ARN
      Name: !Sub "/deploy/${Environment}/auth_certificate_arn"
      Type: String
      Value: !Ref AccountsAuthCertificate
      Tags:
        Environment: !Ref Environment
        Application: "auth-frontend"
        Source: govuk-one-login/authentication-frontend/cloudformation/domains/template.yaml

  #
  # managed
  #
  AccountsManageHostedZone:
    Type: AWS::Route53::HostedZone
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      Name: !Sub manage-sp.${Environment}.account.gov.uk

  AccountsManageHostedZoneSSM:
    Type: AWS::SSM::Parameter
    Properties:
      Description: The Manage subdomain Public Hosted Zone Id
      Name: !Sub "/deploy/${Environment}/manage_route53_hostedzone_id"
      Type: String
      Value: !Ref AccountsManageHostedZone
      Tags:
        Environment: !Ref Environment
        Application: "auth-frontend"
        Source: govuk-one-login/authentication-frontend/cloudformation/domains/template.yaml

  AccountsManageCertificate:
    Type: AWS::CertificateManager::Certificate
    Properties:
      DomainName: !Sub manage-sp.${Environment}.account.gov.uk
      DomainValidationOptions:
        - DomainName: !Sub manage-sp.${Environment}.account.gov.uk
          HostedZoneId: !GetAtt AccountsManageHostedZone.Id
      ValidationMethod: DNS

  AccountsManageCertificateArnSSM:
    Type: AWS::SSM::Parameter
    Properties:
      Description: The Manage Subdomain Certificate ARN
      Name: !Sub "/deploy/${Environment}/manage_certificate_arn"
      Type: String
      Value: !Ref AccountsManageCertificate
      Tags:
        Environment: !Ref Environment
        Application: "auth-frontend"
        Source: govuk-one-login/authentication-frontend/cloudformation/domains/template.yaml
  #
  # oidc
  #
  AccountsOidcHostedZone:
    Type: AWS::Route53::HostedZone
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      Name: !Sub oidc-sp.${Environment}.account.gov.uk

  AccountsOidcHostedZoneSSM:
    Type: AWS::SSM::Parameter
    Properties:
      Description: The Oidc subdomain Public Hosted Zone Id
      Name: !Sub "/deploy/${Environment}/oidc_route53_hostedzone_id"
      Type: String
      Value: !Ref AccountsOidcHostedZone
      Tags:
        Environment: !Ref Environment
        Application: "auth-frontend"
        Source: govuk-one-login/authentication-frontend/cloudformation/domains/template.yaml

  AccountsOidcCertificate:
    Type: AWS::CertificateManager::Certificate
    Properties:
      DomainName: !Sub oidc-sp.${Environment}.account.gov.uk
      DomainValidationOptions:
        - DomainName: !Sub oidc-sp.${Environment}.account.gov.uk
          HostedZoneId: !GetAtt AccountsOidcHostedZone.Id
      ValidationMethod: DNS

  AccountsOidcCertificateArnSSM:
    Type: AWS::SSM::Parameter
    Properties:
      Description: The Oidc subdomain Certificate ARN
      Name: !Sub "/deploy/${Environment}/oidc_certificate_arn"
      Type: String
      Value: !Ref AccountsOidcCertificate
      Tags:
        Environment: !Ref Environment
        Application: "auth-frontend"
        Source: govuk-one-login/authentication-frontend/cloudformation/domains/template.yaml

  #
  # signin
  #
  AccountsSigninHostedZone:
    Type: AWS::Route53::HostedZone
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      Name: !Sub signin-sp.${Environment}.account.gov.uk

  AccountsSigninHostedZoneSSM:
    Type: AWS::SSM::Parameter
    Properties:
      Description: The SignIn subdomain Public Hosted Zone Id
      Name: !Sub "/deploy/${Environment}/signin_route53_hostedzone_id"
      Type: String
      Value: !Ref AccountsSigninHostedZone
      Tags:
        Environment: !Ref Environment
        Application: "auth-frontend"
        Source: govuk-one-login/authentication-frontend/cloudformation/domains/template.yaml

  AccountsSignInCertificate:
    Type: AWS::CertificateManager::Certificate
    Properties:
      DomainName: !Sub signin-sp.${Environment}.account.gov.uk
      DomainValidationOptions:
        - DomainName: !Sub signin-sp.${Environment}.account.gov.uk
          HostedZoneId: !GetAtt AccountsSigninHostedZone.Id
      ValidationMethod: DNS

  AccountsSignInCertificateArnSSM:
    Type: AWS::SSM::Parameter
    Properties:
      Description: The SignIn Domain Certificate ARN
      Name: !Sub "/deploy/${Environment}/signin_certificate_arn"
      Type: String
      Value: !Ref AccountsSignInCertificate
      Tags:
        Environment: !Ref Environment
        Application: "auth-frontend"
        Source: govuk-one-login/authentication-frontend/cloudformation/domains/template.yaml
