name: snapshot-tests

services:
  redis:
    image: redis:6.0.5-alpine
    ports:
      - "${REDIS_PORT:-6379}:6379"
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 1s
      timeout: 3s
      retries: 5
      start_period: 1s

  frontend:
    build:
      context: .
      dockerfile: snapshots-frontend.Dockerfile
    ports:
      - "3001:3000"
    ipc: host
    environment:
      SESSION_SECRET: 000000

      NO_PHOTO_ID_CONTACT_FORMS: 1
      LANGUAGE_TOGGLE_ENABLED: 1
      USE_REBRAND: 1
      SHOW_WALLET_CONTACT_FORM: 1

      REDIS_PORT: 6379
      REDIS_HOST: redis # This is the name of the service in `docker-compose.yml`
    depends_on:
      redis:
        condition: service_healthy
    healthcheck:
      test:  wget --spider http://localhost:3000/healthcheck || exit 1
      interval: 5s
      timeout: 3s
      retries: 5

  playwright:
    build:
      context: .
      dockerfile: snapshots-playwright.Dockerfile
    depends_on:
      frontend:
        condition: service_healthy
    environment:
      WEBSITE_HOST: http://localhost:3001
    volumes:
      - ./src/components/contact-us/tests/contact-us-snapshot.test.ts-snapshots:/app/src/components/contact-us/tests/contact-us-snapshot.test.ts-snapshots
      - ./test-results:/app/test-results
    command:
      npx playwright test ${COMMAND:-}
    network_mode: "host"