FROM node:22.3.0-alpine3.20@sha256:415f3219943ef82fa45988acdaa7df05a0b52cabd3502095c59d34cbe28c1bc1

ENV NODE_ENV "development"
ENV PORT 2000

USER node
WORKDIR /home/node/app
COPY --chown=node:node package.json ./
COPY --chown=node:node yarn.lock ./

RUN yarn install

COPY --chown=node:node dev-app.js ./

EXPOSE $PORT

CMD ["yarn", "dummy-server"]
