FROM node:19.4.0-alpine3.16@sha256:4ceb1b89ced8c3f8098ccc26039be8ebf43f102cd7c4f0d76b46a37c61b345e8

ENV NODE_ENV "development"
ENV PORT 2000

USER node
WORKDIR /home/node/app
COPY --chown=node:node . .

RUN yarn install

EXPOSE $PORT

CMD ["yarn", "dummy-server"]
