services:
  di-auth-frontend:
    container_name: di-authentication-frontend_di-auth-frontend
    build:
      context: .
      dockerfile: local.Dockerfile
    ports:
      - "${DOCKER_FRONTEND_PORT:-3000}:${DOCKER_FRONTEND_PORT:-3000}"
      - "${DOCKER_FRONTEND_NODEMON_PORT:-9230}:${DOCKER_FRONTEND_NODEMON_PORT:-9230}"
    volumes:
      - ./:/app
    env_file:
      - .env
    environment:
      ANALYTICS_COOKIE_DOMAIN: localhost

      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID:?AWS_ACCESS_KEY_ID is required. This should be set by `startup.sh` so there may be an issue with the startup script.}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY:?AWS_SECRET_ACCESS_KEY is required. This should be set by `startup.sh` so there may be an issue with the startup script.}

      # We ignore `.env` values here, as we're using the docker network for redis.
      REDIS_PORT: 6379 # This is the default port for Redis
      REDIS_HOST: redis # This is the name of the service in `docker-compose.yml`

      PORT: ${DOCKER_FRONTEND_PORT:-3000}
    restart: on-failure
    networks:
      - di-net
