FROM node:24.15.0-alpine3.22@sha256:b689d4005875ae167178471a7a622ec2909459a3bbb32277260be1971af7a99f

ENV NODE_ENV "development"
ENV PORT 2000

USER node
WORKDIR /home/node/app
COPY .npmrc ./
COPY --chown=node:node package.json ./
COPY --chown=node:node package-lock.json ./

RUN npm config get ignore-scripts | grep -q "true" || exit 1
RUN npm ci --ignore-scripts

COPY --chown=node:node dev-app-orchstub.js ./
COPY --chown=node:node .env ./

EXPOSE $PORT

CMD ["npm", "run", "dummy-server"]
