name: snapshot-tests

services:
  frontend:
    build:
      context: .
      dockerfile: snapshots-frontend.Dockerfile
    ports:
      - "4401:4401"
    ipc: host
    env_file: ./.env.local
    healthcheck:
      test: wget --spider http://localhost:4401/healthcheck || exit 1
      interval: 5s
      timeout: 3s
      retries: 5

  playwright:
    build:
      context: .
      dockerfile: snapshots-playwright.Dockerfile
    depends_on:
      frontend:
        condition: service_healthy
    environment:
      WEBSITE_HOST: http://localhost:4401
    volumes:
      - ./src:/app/src
      - ./test:/app/test
      - ./test-results:/app/test-results
    command: npx playwright test ${COMMAND:-}
    network_mode: "host"
