server {
    listen 80;
    server_name localhost;

    location = / {
        proxy_pass http://orch-stub-start:4400;
        proxy_set_header Host $host;
    }

    location = /orchestration-redirect {
        proxy_pass http://orch-stub-start:4400;
        proxy_set_header Host $host;
    }

    location / {
        proxy_pass http://authentication-frontend:4401;
        proxy_set_header Host $host;
    }
}
