export const PATH_NAMES = {
  ACCESSIBILITY_STATEMENT: "/accessibility-statement",
  TERMS_AND_CONDITIONS: "/terms-and-conditions",
  PRIVACY_POLICY: "/privacy-statement",
  COOKIES_POLICY: "/cookies",
  SUPPORT: "/support",
  SIGN_IN_OR_CREATE: "/sign-in-or-create",
  ENTER_EMAIL: "/enter-email",
  ENTER_EMAIL_POST_CREATE: "/enter-email-create",
  ACCOUNT_NOT_FOUND: "/account-not-found",
  CHECK_YOUR_EMAIL: "/check-your-email",
  ENTER_PASSWORD: "/enter-password",
  ENTER_PASSWORD_ACCOUNT_EXISTS: "/enter-password-account-exists",
  RESET_PASSWORD_CHECK_EMAIL: "/reset-password-check-email",
  RESET_PASSWORD: "/reset-password",
  RESET_PASSWORD_EXPIRED_LINK: "/reset-password-expired-link",
  RESET_PASSWORD_CONFIRMATION: "/reset-password-confirmed",
  CREATE_ACCOUNT_CHECK_EMAIL: "/check-email",
  CREATE_ACCOUNT_SET_PASSWORD: "/create-password",
  CREATE_ACCOUNT_ENTER_PHONE_NUMBER: "/enter-phone-number",
  CREATE_ACCOUNT_SUCCESSFUL: "/account-created",
  LOG_IN_ENTER_PHONE_NUMBER: "/enter-phone-number",
  CHECK_YOUR_PHONE: "/check-your-phone",
  SHARE_INFO: "/share-info",
  UPDATED_TERMS_AND_CONDITIONS: "/updated-terms-and-conditions",
  UPDATED_TERMS_AND_CONDITIONS_DISAGREE:
    "/updated-terms-and-conditions-disagree",
  ENTER_MFA: "/enter-code",
  SECURITY_CODE_INVALID: "/security-code-invalid",
  SECURITY_CODE_REQUEST_EXCEEDED: "/security-code-requested-too-many-times",
  SECURITY_CODE_WAIT: "/security-code-invalid-request",
  AUTH_CODE: "/auth-code",
  RESEND_MFA_CODE: "/resend-code",
  SIGNED_OUT: "/signed-out",
  ACCOUNT_LOCKED: "/account-locked",
  UPLIFT_JOURNEY: "/uplift",
  INVALID_SESSION: "/invalid-session",
  CONTACT_US: "/contact-us",
  CONTACT_US_SUBMIT_SUCCESS: "/contact-us-submit-success",
  CONTACT_US_POST_SUBMIT: "/contact-us-submit",
};

export const HTTP_STATUS_CODES = {
  NOT_FOUND: 404,
  INTERNAL_SERVER_ERROR: 500,
  BAD_REQUEST: 400,
  UNAUTHORIZED: 401,
  FORBIDDEN: 403,
  OK: 200,
  NO_CONTENT: 204,
  REDIRECT: 303,
};

export const ERROR_CODES = {
  REQUEST_MISSING_PARAMETERS: 1001,
  RESET_PASSWORD_LINK_MAX_RETRIES_REACHED: 1022,
  RESET_PASSWORD_LINK_BLOCKED: 1023,
};

export enum LOCALE {
  EN = "en",
  CY = "cy",
}

export const API_ENDPOINTS = {
  USER_EXISTS: "/user-exists",
  SIGNUP_USER: "/signup",
  SEND_NOTIFICATION: "/send-notification",
  VERIFY_CODE: "/verify-code",
  LOG_IN_USER: "/login",
  UPDATE_PROFILE: "/update-profile",
  MFA: "/mfa",
  AUTH_CODE: "/auth-code",
  CLIENT_INFO: "/client-info",
  RESET_PASSWORD_REQUEST: "/reset-password-request",
  RESET_PASSWORD: "/reset-password",
};

export const ERROR_MESSAGES = {
  FAILED_HTTP_REQUEST: "Failed HTTP request",
  INVALID_CSRF_TOKEN: "Invalid CSRF token",
  INVALID_SESSION: "Invalid session",
  INVALID_HTTP_REQUEST: "Invalid HTTP request",
  FORBIDDEN: "Unauthorized HTTP request",
  INTERNAL_SERVER_ERROR: "Internal server error",
  PAGE_NOT_FOUND: "Request page not found",
};

export const USER_STATE = {
  REQUIRES_TWO_FACTOR: "TWO_FACTOR_REQUIRED",
  USER_NOT_FOUND: "USER_NOT_FOUND",
  EMAIL_CODE_NOT_VALID: "EMAIL_CODE_NOT_VALID",
  EMAIL_CODE_VERIFIED: "EMAIL_CODE_VERIFIED",
  EMAIL_CODE_MAX_RETRIES_REACHED: "EMAIL_CODE_MAX_RETRIES_REACHED",
  AUTHENTICATED: "AUTHENTICATED",
  LOGGED_IN: "LOGGED_IN",
  ADDED_UNVERIFIED_PHONE_NUMBER: "ADDED_UNVERIFIED_PHONE_NUMBER",
  PHONE_NUMBER_VERIFIED: "PHONE_NUMBER_CODE_VERIFIED",
  MFA_CODE_VERIFIED: "MFA_CODE_VERIFIED",
  PHONE_NUMBER_CODE_MAX_RETRIES_REACHED:
    "PHONE_NUMBER_CODE_MAX_RETRIES_REACHED",
  MFA_CODE_MAX_RETRIES_REACHED: "MFA_CODE_MAX_RETRIES_REACHED",
  MFA_CODE_NOT_VALID: "MFA_CODE_NOT_VALID",
  CONSENT_ADDED: "CONSENT_ADDED",
  UPDATED_TERMS_AND_CONDITIONS: "UPDATED_TERMS_AND_CONDITIONS",
  RESET_PASSWORD_LINK_SENT: "RESET_PASSWORD_LINK_SENT",
  ACCOUNT_LOCKED: "ACCOUNT_TEMPORARILY_LOCKED",
  EMAIL_MAX_CODES_SENT: "EMAIL_MAX_CODES_SENT",
  EMAIL_CODE_REQUESTS_BLOCKED: "EMAIL_CODE_REQUESTS_BLOCKED",
  PHONE_NUMBER_MAX_CODES_SENT: "PHONE_NUMBER_MAX_CODES_SENT",
  PHONE_NUMBER_CODE_REQUESTS_BLOCKED: "PHONE_NUMBER_CODE_REQUESTS_BLOCKED",
  PHONE_NUMBER_CODE_NOT_VALID: "PHONE_NUMBER_CODE_NOT_VALID",
  MFA_SMS_MAX_CODES_SENT: "MFA_SMS_MAX_CODES_SENT",
  MFA_CODE_REQUESTS_BLOCKED: "MFA_CODE_REQUESTS_BLOCKED",
  CONSENT_REQUIRED: "CONSENT_REQUIRED",
  PHONE_NUMBER_CODE_VERIFIED: "PHONE_NUMBER_CODE_VERIFIED",
  TWO_FACTOR_REQUIRED: "TWO_FACTOR_REQUIRED",
  UPLIFT_REQUIRED_CM: "UPLIFT_REQUIRED_CM",
  UPDATED_TERMS_AND_CONDITIONS_ACCEPTED:
    "UPDATED_TERMS_AND_CONDITIONS_ACCEPTED",
  VERIFY_PHONE_NUMBER_CODE_SENT: "VERIFY_PHONE_NUMBER_CODE_SENT",
  VERIFY_EMAIL_CODE_SENT: "VERIFY_EMAIL_CODE_SENT",
  AUTHENTICATION_REQUIRED: "AUTHENTICATION_REQUIRED",
  AUTHENTICATION_REQUIRED_ACCOUNT_EXISTS:
    "AUTHENTICATION_REQUIRED_ACCOUNT_EXISTS",
  MFA_SMS_CODE_SENT: "MFA_SMS_CODE_SENT",
};

export const SERVICE_TYPE = {
  MANDATORY: "MANDATORY",
  OPTIONAL: "OPTIONAL",
};

export enum NOTIFICATION_TYPE {
  VERIFY_EMAIL = "VERIFY_EMAIL",
  VERIFY_PHONE_NUMBER = "VERIFY_PHONE_NUMBER",
  ACCOUNT_CREATED_CONFIRMATION = "ACCOUNT_CREATED_CONFIRMATION",
  MFA_SMS = "MFA_SMS",
}

export const COOKIE_CONSENT = {
  ACCEPT: "accept",
  REJECT: "reject",
  NOT_ENGAGED: "not-engaged",
};

export enum SUPPORT_TYPE {
  GOV_SERVICE = "GOV_SERVICE",
  PUBLIC = "PUBLIC",
}

export const ENVIRONMENT_NAME = {
  PROD: "production",
  DEV: "development",
};
