name: Block Package Updates

on:
  pull_request:
    paths:
      - "package.json"
      - "package-lock.json"
      - "yarn.lock"

jobs:
  check-package-changes:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          fetch-depth: 0

      - name: Check for package changes
        run: |
          if git diff --name-only origin/${{ github.base_ref }}..HEAD | grep -E "(package\.json|package-lock\.json|yarn\.lock)"; then
            echo "❌ Package files modified - blocking merge"
            exit 1
          fi
          echo "✅ No package changes detected"
