name: Build and deploy frontend Dev
env:
  AWS_REGION: eu-west-2
  DEPLOYER_ROLE: arn:aws:iam::706615647326:role/deployers/dev-github-actions-publish-to-s3-for-code-signing
  DEV_GHA_DEPLOYER_ROLE: arn:aws:iam::653994557586:role/dev-auth-deploy-pipeline-GitHubActionsRole-QrtGginNnjDD
  DEV_TOOLING_ECR_FRONTEND_REPO: frontend-image-repository
  DEV_BASIC_SIDECAR_ECR_REPO: basic-auth-sidecar-image-repository
  DEV_ARTIFACT_BUCKET: dev-auth-deploy-pipeline-githubartifactsourcebuck-ssdefc91xjh6
  DEV_SERVICE_DOWN_ECR_REPO: service-down-page-image-repository

on:
  workflow_dispatch:

jobs:
  pr-data:
    name: Get data for merged PR
    permissions:
      contents: read
      pull-requests: read
    uses: ./.github/workflows/call_get_pr_data.yml

  build-frontend:
    name: Build and push Frontend
    runs-on: ubuntu-latest
    timeout-minutes: 60
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      - name: Set up Docker CLI
        uses: docker/setup-buildx-action@988b5a0280414f521da01fcc63a27aeeb4b104db # v3.6.1
      - name: Assume AWS DEPLOYER role in tooling acct
        uses: aws-actions/configure-aws-credentials@e3dd6a429d7300a6a4c196c26e071d42e0343502 # v4.0.2
        with:
          role-to-assume: ${{ env.DEPLOYER_ROLE }}
          aws-region: ${{ env.AWS_REGION }}
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@062b18b96a7aff071d4dc91bc00c4c1a7945b076 # v2.0.1
      - name: Login to GDS Dev Dynatrace Container Registry
        uses: docker/login-action@0d4c9c5ea7693da7b068278f7b52bda2a190a446 # v3.2.0
        with:
          registry: khw46367.live.dynatrace.com
          username: khw46367
          password: ${{ secrets.DYNATRACE_PAAS_TOKEN }}
      - name: Build, tag and push frontend
        uses: docker/build-push-action@5176d81f87c23d6fc96624dfdbcd9f3830bbe445 # v6.5.0
        with:
          context: .
          push: true
          tags: "${{ steps.login-ecr.outputs.registry }}/${{ env.DEV_TOOLING_ECR_FRONTEND_REPO }}:${{ github.sha}}"
          cache-from: type=gha
          cache-to: type=gha,mode=max
  build-sidecar:
    name: Build and push Basic Auth Sidecar
    runs-on: ubuntu-latest
    timeout-minutes: 60
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      - name: Set up Docker CLI
        uses: docker/setup-buildx-action@988b5a0280414f521da01fcc63a27aeeb4b104db # v3.6.1
      - name: Assume AWS DEPLOYER role in tooling acct
        uses: aws-actions/configure-aws-credentials@e3dd6a429d7300a6a4c196c26e071d42e0343502 # v4.0.2
        with:
          role-to-assume: ${{ env.DEPLOYER_ROLE }}
          aws-region: ${{ env.AWS_REGION }}
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@062b18b96a7aff071d4dc91bc00c4c1a7945b076 # v2.0.1
      - name: Build, tag, and push basic-auth-sidecar
        uses: docker/build-push-action@5176d81f87c23d6fc96624dfdbcd9f3830bbe445 # v6.5.0
        with:
          context: basic-auth-sidecar
          push: true
          tags: "${{ steps.login-ecr.outputs.registry }}/${{ env.DEV_BASIC_SIDECAR_ECR_REPO }}:${{ github.sha }}"
          cache-from: type=gha
          cache-to: type=gha,mode=max
  build-service-down:
    name: Build and push Service Down Page
    runs-on: ubuntu-latest
    timeout-minutes: 60
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      - name: Set up Docker CLI
        uses: docker/setup-buildx-action@988b5a0280414f521da01fcc63a27aeeb4b104db # v3.6.1
      - name: Assume AWS DEPLOYER role in tooling acct
        uses: aws-actions/configure-aws-credentials@e3dd6a429d7300a6a4c196c26e071d42e0343502 # v4.0.2
        with:
          role-to-assume: ${{ env.DEPLOYER_ROLE }}
          aws-region: ${{ env.AWS_REGION }}
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@062b18b96a7aff071d4dc91bc00c4c1a7945b076 # v2.0.1
      - name: Build, tag, and push service down page
        uses: docker/build-push-action@5176d81f87c23d6fc96624dfdbcd9f3830bbe445 # v6.5.0
        with:
          context: service-down-page-config
          push: true
          tags: "${{ steps.login-ecr.outputs.registry }}/${{ env.DEV_SERVICE_DOWN_ECR_REPO }}:${{ github.sha }}"
          cache-from: type=gha
          cache-to: type=gha,mode=max
  deploy:
    needs:
      - build-frontend
      - build-sidecar
      - build-service-down
      - pr-data
    runs-on: ubuntu-latest
    timeout-minutes: 60
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@e3dd6a429d7300a6a4c196c26e071d42e0343502 # v4.0.2
        with:
          role-to-assume: ${{ env.DEV_GHA_DEPLOYER_ROLE }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Upload frontend Terraform files
        working-directory: ci/terraform
        run: |
          echo "::group::Zip up frontend terraform"
          zip -r frontend.zip .
          echo "::endgroup::"

          echo "::group::Upload artifact to S3"
          OBJECT_VERSION="$(aws s3api put-object \
            --bucket ${{ env.DEV_ARTIFACT_BUCKET }} \
            --key frontend.zip \
            --body frontend.zip \
            --metadata '${{ toJson(fromJson(needs.pr-data.outputs.data)) }}' \
            --query VersionId --output text)"
          echo "::endgroup::"
          echo "::notice title=Final artifact uploaded to S3::object: frontend.zip, version: ${OBJECT_VERSION}"
