name: Build and Deploy frontend

env:
  AWS_REGION: eu-west-2

# Deploy role & Artificate buckets are Logical id  GitHubActionsRole & GitHubArtifactSourceBucket Value from Build Pipeline

on:
  push:
    branches:
      - main

concurrency:
  group: "deploy-frontend"
  cancel-in-progress: false

jobs:
  pr-data:
    name: Get data for merged PR
    permissions:
      contents: read
      pull-requests: read
    uses: ./.github/workflows/call_get_pr_data.yml

  build:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      - name: Assume AWS DEPLOYER role in tooling acct
        uses: aws-actions/configure-aws-credentials@e3dd6a429d7300a6a4c196c26e071d42e0343502 # v4.0.2
        with:
          role-to-assume: ${{ secrets.DEPLOYER_ROLE }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@062b18b96a7aff071d4dc91bc00c4c1a7945b076 # v2.0.1

      - name: Login to GDS Dev Dynatrace Container Registry
        uses: docker/login-action@0d4c9c5ea7693da7b068278f7b52bda2a190a446 # v3.2.0
        with:
          registry: khw46367.live.dynatrace.com
          username: khw46367
          password: ${{ secrets.DYNATRACE_PAAS_TOKEN }}

      - name: Build, tag, and push frontend
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: ${{ secrets.TOOLING_ECR_FRONTEND_REPO }}
        run: |
          docker build -t "${ECR_REGISTRY}/${ECR_REPOSITORY}:${{ github.sha }}" .
          docker push "${ECR_REGISTRY}/${ECR_REPOSITORY}:${{ github.sha }}"

      - name: Build, tag, and push basic-auth-sidecar
        working-directory: basic-auth-sidecar
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: ${{ secrets.BASIC_SIDECAR_ECR_REPO }}
        run: |
          docker build -t "${ECR_REGISTRY}/${ECR_REPOSITORY}:${{ github.sha }}" .
          docker push "${ECR_REGISTRY}/${ECR_REPOSITORY}:${{ github.sha }}"

      - name: Build, tag, and push service down page
        working-directory: service-down-page-config
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: ${{ secrets.SERVICE_DOWN_ECR_REPO }}
        run: |
          docker build -t "${ECR_REGISTRY}/${ECR_REPOSITORY}:${{ github.sha }}" .
          docker push "${ECR_REGISTRY}/${ECR_REPOSITORY}:${{ github.sha }}"

  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    needs:
      - pr-data
      - build
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@e3dd6a429d7300a6a4c196c26e071d42e0343502 # v4.0.2
        with:
          role-to-assume: ${{ secrets.DEPLOY_ROLE }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Upload frontend Terraform files
        working-directory: ci/terraform
        run: |
          echo "::group::Zip up frontend terraform"
          zip -r frontend.zip .
          echo "::endgroup::"

          echo "::group::Upload artifact to S3"
          OBJECT_VERSION="$(aws s3api put-object \
            --bucket ${{ secrets.ARTIFACT_BUCKET }} \
            --key frontend.zip \
            --body frontend.zip \
            --metadata '${{ toJson(fromJson(needs.pr-data.outputs.data)) }}' \
            --query VersionId --output text)"
          echo "::endgroup::"
          echo "::notice title=Final artifact uploaded to S3::object: frontend.zip, version: ${OBJECT_VERSION}"
