name: Build and push Docker image
on:
  workflow_call:
    inputs:
      aws-region:
        description: "AWS region to deploy to"
        default: "eu-west-2"
        type: string
      context:
        description: "The build context. Defaults to repository root"
        default: "."
        type: string
      cache-ecr-repo:
        description: "The name of the ECR repo to use for caching"
        default: "build-cache"
        type: string
    secrets:
      dynatrace_registry:
        description: "The Dynatrace registry to use (just the username)"
      dynatrace_token:
        description: "The Dynatrace token"
      deployer_role:
        description: "The role to assume in the tooling account"
      ecr_repo:
        description: "The name of the ECR repo to push to"

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    permissions:
      id-token: write
      contents: read
    env:
      CACHE_TAG: ${{ inputs.context == '.' && 'root' || inputs.context }}
    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Set up Docker CLI
        uses: docker/setup-buildx-action@d7f5e7f509e45cec5c76c4d5afdd7de93d0b3df5 # v4.1.0

      - name: Assume AWS DEPLOYER role in tooling acct
        uses: aws-actions/configure-aws-credentials@254c19bd240aabef8777f48595e9d2d7b972184b # v6.2.1
        with:
          role-to-assume: ${{ secrets.deployer_role }}
          aws-region: ${{ inputs.aws-region }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@d539f0932e70871a027e9d5a9d8fc38589180a64 # v2.1.6

      - name: Login to GDS Dev Dynatrace Container Registry
        uses: docker/login-action@650006c6eb7dba73a995cc03b0b2d7f5ca915bee # v4.2.0
        with:
          registry: "${{ secrets.dynatrace_registry }}.live.dynatrace.com"
          username: ${{ secrets.dynatrace_registry }}
          password: ${{ secrets.dynatrace_token }}

      - name: Build image metadata
        id: metadata
        if: github
        uses: docker/metadata-action@80c7e94dd9b9319bd5eb7a0e0fe9291e23a2a2e9 # v6.1.0
        with:
          images: |
            "${{ steps.login-ecr.outputs.registry }}/${{ secrets.ecr_repo }}"
          labels: ${{ inputs.context != '.' && format('org.opencontainers.image.title={0}', inputs.context) }}
          tags: |
            type=sha,prefix=,suffix=,format=long
      - name: Build, tag and push image
        uses: docker/build-push-action@f9f3042f7e2789586610d6e8b85c8f03e5195baf # v7.2.0
        env:
          CACHE_IMAGE: ${{ steps.login-ecr.outputs.registry }}/${{ inputs.cache-ecr-repo }}:${{ env.CACHE_TAG }}-cache
        with:
          context: ${{ inputs.context }}
          build-contexts: |
            oneagent_codemodules=docker-image://${{ secrets.dynatrace_registry}}.live.dynatrace.com/linux/oneagent-codemodules-musl:nodejs
          push: true
          labels: ${{ steps.metadata.outputs.labels }}
          tags: ${{ steps.metadata.outputs.tags }}
          cache-from: type=registry,ref=${{ env.CACHE_IMAGE }}
          cache-to: mode=max,image-manifest=true,oci-mediatypes=true,type=registry,ref=${{ env.CACHE_IMAGE }}
