name: Deploy frontend (with SAM Deploy Pipeline)

on:
  push:
    branches:
      - secure-pipeline-action
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build and push basic-auth-sidecar image
        uses: govuk-one-login/devplatform-upload-action-ecr@PSREDEV-1167
        with:
          role-to-assume-arn: ${{ secrets.GH_ACTIONS_ROLE_ARN }}
          container-sign-kms-key-arn: ${{ secrets.CONTAINER_SIGN_KMS_KEY_ARN }}
          build-and-push-image-only: true
          working-directory: basic-auth-sidecar
          artifact-bucket-name: ${{ secrets.ARTIFACT_SOURCE_BUCKET_NAME }}
          ecr-repo-name: ${{ secrets.BASIC_AUTH_SIDECAR_ECR_REPOSITORY }}
          checkout-repo: false

      - name: Build, push and deploy frontend
        uses: govuk-one-login/devplatform-upload-action-ecr@PSREDEV-1167
        with:
          role-to-assume-arn: ${{ secrets.GH_ACTIONS_ROLE_ARN }}
          container-sign-kms-key-arn: ${{ secrets.CONTAINER_SIGN_KMS_KEY_ARN }}
          artifact-bucket-name: ${{ secrets.ARTIFACT_SOURCE_BUCKET_NAME }}
          ecr-repo-name: ${{ secrets.FRONTEND_ECR_REPOSITORY }}
          checkout-repo: false
          private-docker-registry: khw46367.live.dynatrace.com
          private-docker-login-username: khw46367
          private-docker-login-password: ${{ secrets.DYNATRACE_PAAS_TOKEN }}
