name: Deploy frontend (with SAM Deploy Pipeline)

on:
  push:
    branches:
      - main

jobs:
  deploy-service-down-page:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Build and push service down page image
        uses: govuk-one-login/devplatform-upload-action-ecr@5f4cd8b195ad7ae810d60881fa6dbaff1764b5da # v1.3.0
        with:
          role-to-assume-arn: ${{ secrets.GH_ACTIONS_ROLE_ARN }}
          container-sign-kms-key-arn: ${{ secrets.CONTAINER_SIGN_KMS_KEY_ARN }}
          build-and-push-image-only: true
          working-directory: service-down-page-config
          artifact-bucket-name: ${{ secrets.ARTIFACT_SOURCE_BUCKET_NAME }}
          ecr-repo-name: ${{ secrets.SERVICE_DOWN_PAGE_ECR_REPOSITORY }}

  deploy-frontend:
    needs:
      - deploy-service-down-page
    runs-on: ubuntu-latest
    timeout-minutes: 60
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Build, push and deploy frontend
        uses: govuk-one-login/devplatform-upload-action-ecr@5f4cd8b195ad7ae810d60881fa6dbaff1764b5da # v1.3.0
        with:
          role-to-assume-arn: ${{ secrets.GH_ACTIONS_ROLE_ARN }}
          container-sign-kms-key-arn: ${{ secrets.CONTAINER_SIGN_KMS_KEY_ARN }}
          artifact-bucket-name: ${{ secrets.ARTIFACT_SOURCE_BUCKET_NAME }}
          ecr-repo-name: ${{ secrets.FRONTEND_ECR_REPOSITORY }}
          template-file: cloudformation/deploy/template.yaml
          private-docker-registry: khw46367.live.dynatrace.com
          private-docker-login-username: khw46367
          private-docker-login-password: ${{ secrets.DYNATRACE_PAAS_TOKEN }}
          build-contexts: |
            oneagent_codemodules=docker-image://${{ secrets.DYNATRACE_REGISTRY_NAME}}.live.dynatrace.com/linux/oneagent-codemodules-musl:nodejs
