name: Playwright acceptance tests (dev)

on:
  workflow_dispatch:

jobs:
  acceptance:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Run docker tests (dev)
        working-directory: playwright-acceptance-tests
        run: bash scripts/run-docker.sh dev

      - name: Upload reports
        if: always()
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: playwright-acceptance-reports-dev
          path: playwright-acceptance-tests/reports
          if-no-files-found: warn
