name: Test Sidecar Container
on:
  pull_request:
    types:
      - opened
      - reopened
      - ready_for_review
      - synchronize

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 18.x
        uses: actions/setup-node@v4
        with:
          node-version: 18.12.1
      - name: Install dependencies
        run: yarn install
      - name: Run sidecar tests
        run: yarn test:sidecar
